apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service
  namespace: dev
data:
  NODE_ENV: development
  PORT: "3000"
  LOG_LEVEL: debug
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  EMAIL_FROM: "noreply-dev@example.com"
  DB_HOST: pharma-dev-postgres.cyrywaguk6v4.us-east-1.rds.amazonaws.com
