apiVersion: v1
kind: ConfigMap
metadata:
  name: manufacturing-service
  namespace: dev
data:
  SPRING_PROFILES_ACTIVE: dev
  DB_HOST: pharma-dev-postgres.cyrywaguk6v4.us-east-1.rds.amazonaws.com
  LOG_LEVEL: DEBUG
  SERVER_PORT: "8085"
  MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: "health,info,metrics,prometheus"
