apiVersion: v1
kind: ServiceAccount
metadata:
  name: notification-service
  namespace: dev
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service
  namespace: dev
data:
  NODE_ENV: development
  PORT: "3000"
  LOG_LEVEL: debug
  SMTP_HOST: "smtp.example.com"
  SMTP_PORT: "587"
  EMAIL_FROM: "noreply-dev@example.com"
  DB_HOST: pharma-dev-postgres.cyrywaguk6v4.us-east-1.rds.amazonaws.com
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
  namespace: dev
  labels:
    app: notification-service
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
        env: dev
    spec:
      serviceAccountName: notification-service
      securityContext:
        fsGroup: 2000
        runAsNonRoot: true
        runAsUser: 1000
      terminationGracePeriodSeconds: 30
      containers:
        - name: pharma-service
          image: 516209541629.dkr.ecr.us-east-1.amazonaws.com/notification-service:sha-5f9a265
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 3000
              protocol: TCP
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 1000
          envFrom:
            - configMapRef:
                name: notification-service
            - secretRef:
                name: db-credentials
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 3000
            initialDelaySeconds: 20
            periodSeconds: 15
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
            successThreshold: 1
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: dev
  labels:
    app: notification-service
    env: dev
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
      name: http
  selector:
    app: notification-service
